baseURL = 'https://vcvc.nl/'
locale = 'en-NL'
theme = 'hugo-theme-console'
title = 'Van Campen Landschap'

[[module.imports]]
  path = "github.com/mrmierzejewski/hugo-theme-console"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  description = "Landschapsontwerp en -advies voor nutsvoorzieningen"

# Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

 # Set the animation style -- https://animate.style/
 # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

[[params.navlinks]]
  name = "Ontwerp"
  url = "/ontwerp/"

[[params.navlinks]]
  name = "Advies"
  url = "/advies/"

[[params.navlinks]]
  name = "Tuin"
  url = "/tuin/"

[[params.navlinks]]
  name = "Foto"
  url = "/foto/"  

  [[params.navlinks]]
  name = "Over mij"
  url = "/overmij/"