baseURL = 'https://vcvc.nl/'
locale = 'en-NL'
theme = 'hugo-theme-console'
title = 'Van Campen Landscape'

[[module.imports]]
  path = "github.com/mrmierzejewski/hugo-theme-console"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  description = "Landscape design studio specialised in utilities"

# Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

 # Set the animation style -- https://animate.style/
 # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

[[params.navlinks]]
  name = "About"
  url = "/about/"

[[params.navlinks]]
  name = "Portfolio"
  url = "/portfolio/"

[[params.navlinks]]
  name = "Bespoke"
  url = "/bespoke/"

[[params.navlinks]]
  name = "Posts"
  url = "/posts/"

[[params.navlinks]]
  name = "Photos"
  url = "/photos/"  